!--------------------------------------------------------------------------------------------------!
!   CP2K: A general program to perform molecular dynamics simulations                              !
!   Copyright 2000-2026 CP2K developers group <https://cp2k.org>                                   !
!                                                                                                  !
!   SPDX-License-Identifier: GPL-2.0-or-later                                                      !
!--------------------------------------------------------------------------------------------------!

! **************************************************************************************************
!> \brief Range-seperated RI methods for HFX with k-points.
!>        SR: two-centered RI; LR: reciprocal scheme
!> \auhtor SY Wang (mm.yyyy)
! **************************************************************************************************

